project:
  type: website
  output-dir: docs
website:
  title: "SAGID+"
  navbar:
    right:
      - href: index.qmd
        text: Le Projet SAGID
      - text: Axes du SAGID        
        menu:
          - text: Axe 1
            url:  /
          - text: Axe 2
            url:  /
          - text: Axe 3
            url:  /
          - text: Axe 4
            url:  /            
      - href: index.qmd
        text: Publications et Resultats
      - href: people.qmd
        text: Partenaires
  page-footer:
    background: light
    left: "Copyright 2023, ERPI Laboratory <br> Powered by [Quarto](https://quarto.org/) v1.3.24"
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



