---
title: "Axe 2: Nouveaux outils d’orientation stratégique et d’accompagnement à la prise de décision"
subtitle: "Cet axe vise à proposer un système d’évaluation et de recommandation de la durabilité des pratiques de gestion des territoires pour les accompagner dans la mise en place de leurs stratégies d'entretien"
format: 
  html:
    page-layout: full
title-block-banner: assets/banner.jpg
title-block-banner-color: 'white'
description-title: description Axe 2
---

Cet axe de recherche peut lui-même être décomposé en différentes activités:

- La formalisation, la modélisation et la représentation des connaissances. Il s'agit principalement d'identifier les sources de données qui peuvent être utilisées dans le développement des outils.

- Le développement d'une technologie permettant de regrouper l'ensemble des données nécessaires.

- La définition des stratégies de fauchage par l'intelligence artificielle en considérant l'évolution de l'environnement à long terme.

- La conception d'un outil d'orientation stratégique et d'accompagnement à la décision qui regroupera l'ensemble des modèles issus des travaux de recherche développés dans la chaire.

Les avancements et les résultats de cet axe sont actuellement les suivants:

:::: {.columns .column-page-inset}
::: {.column width="80%"}
- Article scientifique: "Multi-objective modelling of a roadside mowing problem: a case study in France" <br>
MIHAITA., A.S., MARCHE, B., CAMARGO, M. & RAHIMI, I. (2022) <br>
Cet article aborde le problème de la planification des trajets optimaux des machines d'entretien au sein d'un territoire dédié afin de répondre à plusieurs critères objectifs tels que : minimiser la distance de déplacement, le nombre de machines d'entretien, ainsi que minimiser le temps et le coût associés à chaque campagne d'entretien.
:::
::: {.column width="20%"}
[Lien vers l'article](https://ieeexplore.ieee.org/document/10033303){target="_blank"}
:::
::::

:::: {.columns .column-page-inset}
::: {.column width="80%"}
- Article scientifique: "Identification of sensor technologies with the potential to support roadside ecosystem services" <br>
CORRIGEUX, B., MARCHE, B., CAMARGO, M., BACHMANN, C., & CHAUDRON, C. (2022) <br>
Le but de cette revue est d'identifier des solutions technologiques permettant de réduire les effets de l'entretien sur les services écosystémiques fournis par les bords de route
:::
::: {.column width="20%"}
[Lien vers l'article](https://ieeexplore.ieee.org/document/10033185){target="_blank"}
:::
::::

:::: {.columns .column-page-inset}
::: {.column width="80%"}
- Article scientifique: "Towards Smart and Suitable Management of Roadsides: System Dynamics in the Era of Industry 4.0." <br>
BAUTISTA RODRIGUEZ S., MARCHE B., HAMDANI, F.E., CAMARGO M., MAYER F., BACHMANN C., MONTICOLO D. (2020) <br>
Cet article propose l'intégration d'un processus basé sur la théorie des systèmes dynamiques et le paradigme de l'Industrie 4.0 pour parvenir à une gestion durable des bords de route. Cela nous permettra d'identifier et de gérer de manière appropriée la quantité variable et hétérogène de données qu'implique ce type de système. Le modèle proposé aidera les décideurs politiques des territoires à prendre des actions durables afin de garantir des décisions efficaces dans une vision à long terme, d'évaluer la situation actuelle et les opportunités futures, puis de contribuer à l'évolution des territoires vers une économie circulaire.
:::
::: {.column width="20%"}
[Lien vers l'article](https://doi.org/10.1016/j.susoc.2020.12.001){target="_blank"}
:::
::::



