# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Le projet SAGID+
    url: '#about'
    weight: 10
  - name: Participez au projet !
    url: '/participation'
    weight: 20
  - name: Les axes du projet
    url: '#projects'
    weight: 30
  - name: Talks
    url: '#talks'
    weight: 40
  - name: Actualités et événements
    url: '#featured'
    weight: 50
  - name: Partenaires
    url: '#contact'
    weight: 60
  - name: Contact
    url: '#contact'
    weight: 70
    

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
