# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: SAGID+
    url: '/#banner'
    weight: 10
  #- name: Participez au projet !
  #  url: '/participation'
  #  weight: 20
  - name: Les axes du projet
    identifier: axes
    weight: 30
  - name: "Axe 1: Évaluation des services écosystémiques rendus par les bords de route"
    parent: axes
    url: axe-1/
    weight: 10
  - name: "Axe 2: Nouveaux outils d'orientation stratégique et d'accompagnement à la prise de décision"
    parent: axes
    url: axe-2/
    weight: 20 
  - name: "Axe 3: Intégration dans les nouvelles filières de la bioéconomie"
    parent: axes
    url: axe-3/
    weight: 30 
  - name: "Axe 4: Accompagnement des territoires dans l'évolution des pratiques"
    parent: axes
    url: axe-4/
    weight: 40 

  - name: Actualités et événements
    url: '/post'
    weight: 40
  - name: Communauté
    url: 'communaute/'
    weight: 60
  - name: Contact
    url: 'contact/'
    weight: 70
    

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
