# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: SAGID+
    url: 'en/'
    weight: 10
  - name: Participe to this project !
    url: 'en/participation'
    weight: 20
  - name: Axes of the project
    identifier: axes
    weight: 30
  - name: "Axis 1: Assessment of Ecosystem Services Provided by Roadside Areas"
    parent: axes
    url: en/axes/axe-1-en/
    weight: 10
  - name: "Axis 2: New Tools for Strategic Guidance and Decision Support"
    parent: axes
    url: en/axes/axe-2-en/
    weight: 20 
  - name: "Axis 3: Integration into New Bioeconomy Sectors" 
    parent: axes
    url: en/axes/axe-3-en/
    weight: 30 
  - name: "Axis 4: Supporting Territories in the Evolution of Practices"
    parent: axes
    url: en/axes/axe-4-en/
    weight: 40 

  - name: News and events
    url: 'en/post/'
    weight: 40
  - name: About us
    url: 'communaute/'
    weight: 60
  - name: Contact
    url: 'contact/'
    weight: 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
