# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: SAGID+
    url: 'en/'
    weight: 10
  - name: Participe to this project !
    url: 'en/participation'
    weight: 20
  - name: Les axes du projet
    identifier: axes
    weight: 30
  - name: "Axe 1: Services Ecosystemiques"
    parent: axes
    url: en/axes/axe-1/
    weight: 10
  - name: "Axe 2: OUtils d'orientation"
    parent: axes
    url: en/axes/axe-2/
    weight: 20 
  - name: "Axe 3: Filière bioeconomie"
    parent: axes
    url: en/axes/axe-3/
    weight: 30 
  - name: "Axe 4: Territoire"
    parent: axes
    url: en/axes/axe-4/
    weight: 30 

  - name: Actualités et événements
    url: 'en/post/'
    weight: 40
  - name: Communauté
    url: 'communaute/'
    weight: 60
  - name: Contact
    url: 'contact/'
    weight: 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
